---
#
# Ansible managed
#
language: python

python:
  - "3.7"

services:
  - docker

env:
  global:
    namespace="robertdebock"
  matrix:
    - image="alpine" tag="latest"
    - image="alpine" tag="edge"
    - image="amazonlinux" tag="1"
    - image="centos" tag="7"
    - image="centos" tag="latest"
    - image="debian" tag="latest"
    - image="debian" tag="bullseye"
    - image="fedora" tag="31"
    - image="fedora" tag="latest"
    - image="opensuse" tag="latest"
    - image="ubuntu" tag="latest"
    - image="ubuntu" tag="bionic"
    - image="ubuntu" tag="xenial"

cache:
  - pip

install:
  - pip install --upgrade pip
  - pip install tox

script:
  - tox --parallel all

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  slack:
    secure: "lT4CCTf9ZI1bgIiSybZfYM+W9z4HbMJLxonNNyWJBWBOwqIoHmHR4WK0l3tCjNjX7OkcV+RRZF6wtw6nyr6AY35bN0eYVIHgmGu2Buw5t6nufv/CmK3U/lsXNUhZwG6k1tUKDpCzLcohnfIuoz6U/wjIlR9/uKcUInnr+C3TGg7KrNM8Z5zCVRvnjfLkLN3ixt+3I+ntPGQbAmpQ9Kg1FtvNiiI/JTMfp9B4e7l9ihR/1mtLLQS0JYoTiA3qa8z1qxGJg1P1V90GHHTtKjhi4x00bomqDz1wEyfz38y9OHAHu9zSjjDw5QXzP3OoK2FENbfqsuLAGazCXBktwz1M+ovJP8UVT801U160BD4fqsMUWrfLSTWX2LahZRXER/P/POVlMH+w8SOplRqc5uRNA5HKRdCXgEQCNkaiUJ1bnG8TcKMeFGTjUfTRSD0iM8mIMSckuk6mgq/j+f2R/ONJYGvM9CI7LMTwOWMkRBmSgLb5CXiaDmmMtCCPLbKqIScKua0swKJN6DiXfUfFPfmw5M8fG539E/cW/FAIUfK8rWbdABHy3p8g5KMdhnnHY2B9RlBZNLEBDfhiba3KR5nAeZN2/sSrKCRi8WkoONXbWSknOZE8/8/B4W42JAUDcHQUzLhVX+oemfSGCkaeobkLZLAtHe5iCnM8LYikC7OGj70="
  email: false
