---
# tasks file for rpmfusion
- name: install free repositories
  package:
    name: "{{ rpmfusion_free_repository }}"
    state: present
  register: rpmfusion_install_free_repositories
  until: rpmfusion_install_free_repositories is succeeded
  retries: 3
  when:
    - rpmfusion_free | bool
    - ansible_os_family == "RedHat"

- name: install nonfree repositories
  package:
    name: "{{ rpmfusion_nonfree_repository }}"
    state: present
  register: rpmfusion_install_nonfree_repositories
  until: rpmfusion_install_nonfree_repositories is succeeded
  retries: 3
  when:
    - rpmfusion_nonfree | bool
    - ansible_os_family == "RedHat"
