---
# tasks file for rpmfusion
- name: include assert.yml
  include_tasks: assert.yml

- name: install free repositories
  yum:
    name: "{{ rpmfusion_free_repository }}"
    state: present
    validate_certs: no
  when:
    - rpmfusion_free | bool
    - ansible_os_family == "RedHat"

- name: install nonfree repositories
  yum:
    name: "{{ rpmfusion_nonfree_repository }}"
    state: present
    validate_certs: no
  when:
    - rpmfusion_nonfree | bool
    - ansible_os_family == "RedHat"
